/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditTasks: typeof import('./src/components/EditTasks.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TaskAdd: typeof import('./src/components/TaskAdd.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TaslList: typeof import('./src/components/TaslList.vue')['default']
  }
}
